version: '3'

volumes:
  casm_db:
    external: true

services:
    web:
        image: centos:latest
        container_name: casm
        restart: unless-stopped
        ports:
          - "5003:5003"
        entrypoint: ["curl", "https://raw.githubusercontent.com/tsaitang404/CASM/master/misc/setup-casm.sh > install.sh && bash install.sh"]
        environment:
          - LANG=en_US.UTF-8
          - TZ=Asia/Shanghai
